export const FETCH_USERS = 'FETCH_USERS';
export const CLEAR_OPPONENTS = 'CLEAR_OPPONENTS';
export const SELECT_OPPONENT = 'SELECT_OPPONENT';
export const LOGIN = 'LOGIN';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
